# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.20'
    
        - name: Build
          run: go build -v -C src/boop

        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@master
          with:
            version: latest
            args: release --rm-dist --snapshot
            workdir: ./src/boop
          env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
        - name: GH Release
          uses: softprops/action-gh-release@v0.1.15
          with:
            name: boop-release
            # Repository to make releases against, in <owner>/<repo> format
            repository: LiamBaisley/boop
            # Authorized secret GitHub Personal Access Token. Defaults to github.token
            token: ${{ secrets.PAT }}
            tag: boop-release
            files:
              dist\boop_linux_386\boop
              dist\boop_linux_amd64_v1\boop
              dist\boop_darwin_amd64_v1\boop
              dist\boop_darwin_arm64\boop
              dist\boop_windows_amd64_v1\boop.exe
              dist\boop_windows_arm64\boop.exe
              dist\boop_windows_386\boop.exe
                  
